2020-01-06 06:08:38,620 ERROR: Exception on /index [GET] [in /home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/roan/Documents/Scripts/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', systems=systems)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/roan/Documents/Scripts/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/roan/Documents/Scripts/microblog/app/templates/index.html", line 14, in root
  File "/home/roan/Documents/Scripts/microblog/app/templates/base.html", line 55, in root
  File "/home/roan/Documents/Scripts/microblog/app/templates/index.html", line 40, in block_content
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2020-01-06 06:09:00,992 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:09:01,997 ERROR: Exception on /index [GET] [in /home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/roan/Documents/Scripts/microblog/app/routes.py", line 32, in index
    return render_template('index.html', title='Home', systems=systems)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/roan/Documents/Scripts/microblog/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/roan/Documents/Scripts/microblog/app/templates/index.html", line 14, in root
  File "/home/roan/Documents/Scripts/microblog/app/templates/base.html", line 55, in root
  File "/home/roan/Documents/Scripts/microblog/app/templates/index.html", line 30, in block_content
  File "/home/roan/Documents/Scripts/microblog/app/templates/_post.html", line 12, in root
  File "/home/roan/Documents/Scripts/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'post' is undefined
2020-01-06 06:10:24,198 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:12:15,997 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:15:20,437 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:17:18,048 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:17:41,585 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:20:37,573 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:21:17,553 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
2020-01-06 06:22:56,480 INFO: Microblog startup [in /home/roan/Documents/Scripts/microblog/app/__init__.py:43]
